import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Providers";
import { Toaster } from './../components/ui/toaster';
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
  userScalable: false
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className,"h-screen max-w-screen")}>
        <div className="flex-1" ><Provider>{children}</Provider></div>
        <Toaster/>
      </body>
    </html>
  );
}
